DROP TABLE FBM_USERS;
CREATE TABLE FBM_USERS(
SEQ NUMBER NOT NULL
, ID VARCHAR2(15) NOT NULL
, PW VARCHAR2(20) NOT NULL
, NAME VARCHAR2(10) NOT NULL
);

DROP SEQUENCE FBM_USERS_SEQ;
CREATE SEQUENCE FBM_USERS_SEQ;

--팀원
DROP TABLE PLAYER;

CREATE TABLE PLAYER(
PLAYER_ID NUMBER NOT NULL
, PLAYER_NM VARCHAR2(20) NOT NULL
, TEAM_ID VARCHAR2(4)
, BACK_NO NUMBER
, CAPTAIN CHAR(1)
, CONSTRAINT PK_PLAYER PRIMARY KEY(PLAYER_ID)
);

DROP SEQUENCE SEQ_PLAYER_ID;

CREATE SEQUENCE SEQ_PLAYER_ID;
--팀원

-- 시즌관리
DROP TABLE SEASON;

CREATE TABLE SEASON(
SEASON_ID NUMBER NOT NULL
, SEASON_NM VARCHAR2(20) NOT NULL
, TOT_GAMES NUMBER NOT NULL
, MANAGER_ID VARCHAR2(15) NOT NULL
, CONSTRAINT PK_SEASON PRIMARY KEY(SEASON_ID)
);

DROP SEQUENCE SEQ_SEASON_ID;

CREATE SEQUENCE SEQ_SEASON_ID;
-- 시즌관리

--팀
DROP TABLE TEAM;

CREATE TABLE TEAM(
TEAM_ID NUMBER NOT NULL
, TEAM_NM VARCHAR2(20) NOT NULL
, SEASON_ID VARCHAR2(4) NOT NULL
, CONSTRAINT PK_TEAM PRIMARY KEY(TEAM_ID)
);

DROP SEQUENCE SEQ_TEAM_ID;

CREATE SEQUENCE SEQ_TEAM_ID;
--팀

-- 경기 기록
DROP TABLE RECORD_GAME;

CREATE TABLE RECORD_GAME(
RG_SEQ NUMBER NOT NULL
, SEASON_ID VARCHAR2(4) NOT NULL
, H_TEAM_ID VARCHAR2(3) NOT NULL
, A_TEAM_ID VARCHAR2(3) NOT NULL
, W_TEAM_ID VARCHAR2(3)
, L_TEAM_ID VARCHAR2(3)
, H_TEAM_GOALS NUMBER DEFAULT 0
, A_TEAM_GOALS NUMBER DEFAULT 0
, CONSTRAINT PK_RECORD_GAME PRIMARY KEY(RG_SEQ)
);

DROP SEQUENCE SEQ_RG_SEQ;

CREATE SEQUENCE SEQ_RG_SEQ;
-- 경기 기록

-- 득점 기록
DROP TABLE RECORD_PLAYER;

CREATE TABLE RECORD_PLAYER(
RP_SEQ NUMBER NOT NULL
, SEASON_ID VARCHAR2(4) NOT NULL
, RG_SEQ NUMBER NOT NULL
, TEAM_ID NUMBER NOT NULL
, PLAYER_ID NUMBER NOT NULL
, STARTING CHAR(1)
, GOAL NUMBER
, GOAL_TIME DATE
, CHANGE_IN CHAR(1)
, CHANGE_IN_TIME DATE
, CHANGE_OUT CHAR(1)
, CHANGE_OUT_TIME DATE
, PLAY_TIME NUMBER
, CONSTRAINT PK_RECORD_PLAYER PRIMARY KEY(RP_SEQ)
);

DROP SEQUENCE SEQ_RP_SEQ;

CREATE SEQUENCE SEQ_RP_SEQ;
-- 득점 기록

-- 시즌순위표
CREATE OR REPLACE VIEW SEASON_RANK
AS
SELECT SEASON_NM
       , RANK() OVER(ORDER BY W_POINT DESC, GD DESC, GF DESC, GA ASC) RANK
       , TEAM_NM
       , GAME_CNT
       , W_POINT
       , WIN
       , DRAW
       , LOSE
       , GD
       , GF
       , GA
FROM       
       (
        SELECT SEASON_NM
               , TEAM_NM
               , GAME_CNT
               , WIN * 3 + DRAW * 1 W_POINT
               , WIN
               , DRAW
               , LOSE
               , GF - GA GD
               , GF
               , GA
        FROM   (
                SELECT SS.SEASON_NM SEASON_NM
                       , TM.TEAM_NM TEAM_NM
                       , (SELECT COUNT(ROWNUM) FROM RECORD_GAME WHERE TM.TEAM_ID IN(H_TEAM_ID, A_TEAM_ID)) GAME_CNT
                       , (SELECT COUNT(ROWNUM) FROM RECORD_GAME WHERE W_TEAM_ID = TM.TEAM_ID) WIN
                       , (SELECT COUNT(ROWNUM) FROM RECORD_GAME WHERE W_TEAM_ID = 0 AND TM.TEAM_ID IN(H_TEAM_ID, A_TEAM_ID)) DRAW
                       , (SELECT COUNT(ROWNUM) FROM RECORD_GAME WHERE W_TEAM_ID != TM.TEAM_ID AND W_TEAM_ID != 0 AND TM.TEAM_ID IN(H_TEAM_ID, A_TEAM_ID)) LOSE
                       , ((SELECT SUM(H_TEAM_GOALS) FROM RECORD_GAME WHERE H_TEAM_ID = TM.TEAM_ID) + (SELECT SUM(A_TEAM_GOALS) FROM RECORD_GAME WHERE A_TEAM_ID = TM.TEAM_ID)) GF
                       , ((SELECT SUM(A_TEAM_GOALS) FROM RECORD_GAME WHERE H_TEAM_ID = TM.TEAM_ID) + (SELECT SUM(H_TEAM_GOALS) FROM RECORD_GAME WHERE A_TEAM_ID = TM.TEAM_ID)) GA
                FROM SEASON SS
                     , TEAM TM
                WHERE SS.SEASON_ID = TM.SEASON_ID));
-- 시즌순위표

-- 시즌순위표_NEW
CREATE OR REPLACE VIEW SEASON_RANK
AS
SELECT SEASON_NM
       , RANK() OVER(ORDER BY W_POINT DESC, GD DESC, GF DESC, GA ASC) RANK
       , TEAM_NM
       , GAME_CNT
       , W_POINT
       , WIN
       , DRAW
       , LOSE
       , GD
       , GF
       , GA
FROM       
       (
        SELECT SEASON_NM
               , TEAM_NM
               , GAME_CNT
               , WIN * 3 + DRAW * 1 W_POINT
               , WIN
               , DRAW
               , LOSE
               , GF - GA GD
               , GF
               , GA
        FROM   (
                SELECT SS.SEASON_NM
                       , TM.TEAM_ID
                       , TM.TEAM_NM
                       , SUM(CASE WHEN RG.H_TEAM_ID = TM.TEAM_ID THEN 1
                                  WHEN RG.A_TEAM_ID = TM.TEAM_ID THEN 1 END) GAME_CNT
                       , SUM(CASE WHEN RG.W_TEAM_ID = TM.TEAM_ID THEN 1 ELSE 0 END) WIN
                       , SUM(CASE WHEN RG.W_TEAM_ID = 0 AND TM.TEAM_ID IN(H_TEAM_ID, A_TEAM_ID) THEN 1 ELSE 0 END) DRAW
                       , SUM(CASE WHEN RG.L_TEAM_ID = TM.TEAM_ID THEN 1 ELSE 0 END) LOSE
                       , SUM(CASE WHEN RG.H_TEAM_ID = TM.TEAM_ID AND H_TEAM_GOALS != 0 THEN H_TEAM_GOALS 
                                  WHEN RG.A_TEAM_ID = TM.TEAM_ID AND A_TEAM_GOALS != 0 THEN A_TEAM_GOALS END) GF
                       , SUM(CASE WHEN RG.H_TEAM_ID = TM.TEAM_ID AND A_TEAM_GOALS != 0 THEN A_TEAM_GOALS 
                                  WHEN RG.A_TEAM_ID = TM.TEAM_ID AND H_TEAM_GOALS != 0 THEN H_TEAM_GOALS END) GA                                                
                FROM RECORD_GAME RG
                     , TEAM TM
                     , SEASON SS
                WHERE SS.SEASON_ID = RG.SEASON_ID
                AND SS.SEASON_ID = 1
                GROUP BY SS.SEASON_NM, TM.TEAM_ID, TM.TEAM_NM
                ORDER BY TEAM_ID ASC
                ));
-- 시즌순위표_NEW

                
-- 시즌순위표_FINAL
CREATE OR REPLACE VIEW SEASON_RANK
AS
SELECT SEASON_NM
       , RANK() OVER(ORDER BY W_POINT DESC, GD DESC, GF DESC, GA ASC) RANK
       , TEAM_NM
       , GAME_CNT
       , W_POINT
       , WIN
       , DRAW
       , LOSE
       , GD
       , GF
       , GA
FROM   (
       SELECT SEASON_NM
               , TEAM_NM
               , GAME_CNT
               , WIN * 3 + DRAW * 1 W_POINT
               , WIN
               , DRAW
               , LOSE
               , GF - GA GD
               , GF
               , GA
        FROM   (
        		SELECT ST.SEASON_NM
				       , ST.TEAM_ID
				       , ST.TEAM_NM
				       , SUM(CASE WHEN RG.H_TEAM_ID = ST.TEAM_ID THEN 1
				                  WHEN RG.A_TEAM_ID = ST.TEAM_ID THEN 1 ELSE 0 END) GAME_CNT
				       , SUM(CASE WHEN RG.W_TEAM_ID = ST.TEAM_ID THEN 1 ELSE 0 END) WIN
				       , SUM(CASE WHEN RG.W_TEAM_ID = 0 AND ST.TEAM_ID IN(RG.H_TEAM_ID, RG.A_TEAM_ID) THEN 1 ELSE 0 END) DRAW
				       , SUM(CASE WHEN RG.L_TEAM_ID = ST.TEAM_ID THEN 1 ELSE 0 END) LOSE
				       , SUM(CASE WHEN RG.H_TEAM_ID = ST.TEAM_ID AND RG.H_TEAM_GOALS != 0 THEN RG.H_TEAM_GOALS 
				                  WHEN RG.A_TEAM_ID = ST.TEAM_ID AND RG.A_TEAM_GOALS != 0 THEN RG.A_TEAM_GOALS ELSE 0 END) GF
				       , SUM(CASE WHEN RG.H_TEAM_ID = ST.TEAM_ID AND RG.A_TEAM_GOALS != 0 THEN RG.A_TEAM_GOALS 
				                  WHEN RG.A_TEAM_ID = ST.TEAM_ID AND RG.H_TEAM_GOALS != 0 THEN RG.H_TEAM_GOALS ELSE 0 END) GA
				FROM (
						SELECT SS.SEASON_ID SEASON_ID
						       , SS.SEASON_NM SEASON_NM
						       , TM.TEAM_ID TEAM_ID
						       , TM.TEAM_NM TEAM_NM                                              
						FROM TEAM TM
						     , SEASON SS
						WHERE SS.SEASON_ID = TM.SEASON_ID
				) ST
				LEFT OUTER JOIN RECORD_GAME RG
				ON ST.SEASON_ID = RG.SEASON_ID
				GROUP BY ST.SEASON_ID, ST.SEASON_NM, ST.TEAM_ID, ST.TEAM_NM
				)
		)
ORDER BY TEAM_NM ASC;
-- 시즌순위표_FINAL

/*
-- 팀 기록
DROP TABLE RECORD_TEAM;

CREATE TABLE RECORD_TEAM(
RT_SEQ NUMBER NOT NULL
, RG_SEQ NUMBER NOT NULL
, TEAM_ID VARCHAR2(3) NOT NULL
, GOALS NUMBER  DEFAULT 0
, CONSTRAINT PK_RECORD_TEAM PRIMARY KEY(RT_SEQ)
);

DROP SEQUENCE SEQ_RECORD_TEAM;

CREATE SEQUENCE SEQ_RECORD_TEAM;
-- 팀 기록
*/

